<a href="https://colab.research.google.com/github/JakeOh/202511_BD53/blob/main/lab_python/da01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터 분석 패키지(라이브러리)

*   NumPy: 다차원 배열을 쉽게 사용할 수 있도록 만들어진 패키지. 머신러닝에서 중요하게 사용됨.
*   pandas: 시리즈(Series)와 데이터프레임(DataFrame)을 기본으로 사용해서 데이터 분석에 필요한 기능들을 가지고 있는 패키지.
*   matplotlib, seaborn: 데이터 시각화(그래프) 패키지.
*   scikit-learn: 머신러닝(Machine Learning) 패키지.
*   keras: 딥러닝(Deep Learning) 패키지.


In [1]:
import numpy as np
import pandas as pd
import matplotlib
import seaborn as sns
import sklearn  # scikit-learn 패키지
import keras

In [3]:
print('numpy version =', np.__version__)
print('pandas version =', pd.__version__)
print('matplotlib version =', matplotlib.__version__)
print('seaborn version =', sns.__version__)
print('sklearn version =', sklearn.__version__)
print('keras version =', keras.__version__)

numpy version = 2.0.2
pandas version = 2.2.2
matplotlib version = 3.10.0
seaborn version = 0.13.2
sklearn version = 1.6.1
keras version = 3.10.0


# Python `list` 클래스

*   여러개의 값들을 저장할 수 있는 데이터 타입.
*   인덱스를 기반으로 한 데이터 타입.
    *   indexing: 인덱스를 사용해서 리스트의 특정 위치의 값을 참조. (예) `list[0]`
    *   slicing: [start, end) 인덱스 범위의 리스트를 잘라냄. (예) `list[0:5]`
*   산술 연산
    *   `list + list`: concatenate. 리스트 이어붙이기.
    *   `list * int, int * list`: replicate. 리스트의 원소들을 정수만큼 복사.

In [4]:
numbers1 = [1, 2, 3]
numbers2 = [11, 22, 33]

In [5]:
print(numbers1)

[1, 2, 3]


In [6]:
numbers2

[11, 22, 33]

In [7]:
# indexing
print(numbers1[0])  # 리스트의 첫번째 원소
print(numbers1[-1])  # 리스트의 마지막 원소

1
3


In [8]:
# slicing
print(numbers2[:2])  # 리스트에서 첫 2개 원소들을 잘라내기
print(numbers2[-2:])  # 리스트에서 마지막 2개 원소들을 잘라내기

[11, 22]
[22, 33]


In [9]:
numbers1 + numbers2

[1, 2, 3, 11, 22, 33]

In [11]:
numbers1 * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [13]:
# numbers1과 numbers2의 같은 인덱스에 있는 원소들끼리 덧셈 --> 결과 [1+11, 2+22, 3+33]
[x + y for x, y in zip(numbers1, numbers2)]

[12, 24, 36]

In [14]:
# numbers1의 모든 원소에 3을 곱함. --> 결과 [1*3, 2*3, 3*3]
[3 * x for x in numbers1]

[3, 6, 9]

In [16]:
# numbers1과 numbers2의 같은 인덱스에 있는 원소들끼리 곱셈 --> 결과 [1*11, 2*22, 3*33]
[x * y for x, y in zip(numbers1, numbers2)]

[11, 44, 99]

# NumPy(Numerical Python)

*   다차원배열(n-dimensional array)을 쉽고 빠르게 연산(`+, -, *, /, ...`)하기 위한 패키지.
*   numpy 패키지의 대부분의 기능들(연산자, 함수, 메서드 등)은 반복문의 기능을 가지고 있음.
    *   같은 인덱스의 원소들끼리(element-wise) 연산하는 기능을 가지고 있음.
*   `numpy.ndarray` 클래스: numpy 패키지의 가장 기본이 되는 클래스.


In [17]:
num_array1 = np.array([1, 2, 3, 4, 5])

In [18]:
type(num_array1)

numpy.ndarray

In [19]:
print(num_array1)  # ndarray 클래스의 __str__() 메서드가 리턴하는 문자열을 출력

[1 2 3 4 5]


In [20]:
num_array1  # ndarray 클래스의 __repr__() 메서드가 리턴하는 문자열을 출력

array([1, 2, 3, 4, 5])

In [21]:
num_array2 = np.array([10, 20, 30, 40, 50])

In [22]:
# element-wise(같은 인덱스의 원소들끼리) 연산
print(num_array1 + num_array2)  # [1+10, 2+20, 3+30, ...]
print(num_array1 - num_array2)  # [1-10, 2-20, 3-30, ...]
print(num_array1 * num_array2)  # [1*10, 2*20, 3*30, ...]
print(num_array1 * 3)
print(num_array1 / num_array2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[ 3  6  9 12 15]
[0.1 0.1 0.1 0.1 0.1]
