<a href="https://colab.research.google.com/github/JakeOh/202511_BD53/blob/main/lab_python/da11_index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

# Series 인덱스

## 단일 계층 인덱스

In [44]:
s = pd.Series(data=np.random.rand(5), name='rand_num')
#> Series 객체도 (데이터프레임의 컬럼처럼) 값들의 이름을 설정할 수 있음.
s

0    0.798166
1    0.409831
2    0.574669
3    0.059200
4    0.086920
Name: rand_num, dtype: float64

In [45]:
s.index  #> Series 객체가 가지고 있는 index 속성

RangeIndex(start=0, stop=5, step=1)

In [46]:
s.values  #> Series 객체가 가지고 있는 values 속성 -> 값들을 아이템으로 갖는 1차원 ndarray(배열)

array([0.79816619, 0.40983127, 0.57466882, 0.05919979, 0.08692045])

In [47]:
s.loc[0]  #> 인덱스 0 위치의 값

np.float64(0.7981661880484631)

In [48]:
s.loc[[0, 4]]  #> 인덱스 0, 4 위치의 값들

0    0.798166
4    0.086920
Name: rand_num, dtype: float64

In [49]:
s = pd.Series(data=np.random.randint(100, size=5), name='score',
              index=['scott', 'allen', 'king', '홍길동', '오쌤'])
s

scott    28
allen    57
king     74
홍길동      60
오쌤       78
Name: score, dtype: int64

In [50]:
s.index

Index(['scott', 'allen', 'king', '홍길동', '오쌤'], dtype='object')

In [51]:
s.values

array([28, 57, 74, 60, 78])

In [52]:
s.index.nlevels  # 인덱스의 레벨(계층) 개수

1

In [53]:
s.loc['홍길동']  #> 해당 인덱스의 값 1개

np.int64(60)

In [54]:
s.loc[['scott', '홍길동']]  #> 해당 인덱스들의 값들

scott    28
홍길동      60
Name: score, dtype: int64

## 계층적 인덱스(hierachical index), multi-level index

In [55]:
s = pd.Series(data=np.random.randint(100, size=6), name='score',
              index=[['m', 'm', 'm', 'f', 'f', 'f'], ['a', 'b', 'c', 'a', 'b', 'c']])
s

m  a    48
   b    77
   c    30
f  a     0
   b     7
   c    95
Name: score, dtype: int64

In [56]:
s.values  #> 1차원 배열(ndarray)

array([48, 77, 30,  0,  7, 95])

In [57]:
s.index  #> MultiIndex - 튜플들을 아이템으로 갖는 배열

MultiIndex([('m', 'a'),
            ('m', 'b'),
            ('m', 'c'),
            ('f', 'a'),
            ('f', 'b'),
            ('f', 'c')],
           )

In [58]:
s.index.nlevels  #> 계층(level)들의 개수

2

In [38]:
s.iloc[-1]

np.int64(40)

### Multi-level index에서 indexing, slicing

nlevels(인덱스의 계층 개수)가 2개 이상인 multi-level 인덱스를 loc 속성에서 사용할 때,
*   첫번째 계층(level)의 인덱스만 가지고 indexing과 slicing을 할 수 있음.
*   두번째 계층의 인덱스만 가지고는 indexing/slicing을 할 수 없음!
*   튜플 형태의 인덱스로 indexing/slicing을 할 수 있음.


In [39]:
s

m  a    37
   b    95
   c    96
f  a    48
   b     3
   c    40
Name: score, dtype: int64

In [33]:
s.loc['m']  # 첫번째 계층(level)의 인덱스로  indexing.

a     5
b    98
c    72
Name: score, dtype: int64

In [41]:
s.loc['f']

a    48
b     3
c    40
Name: score, dtype: int64

In [ ]:
s.loc['a']  #> KeyError - 'a'는 첫번째 계층(level)의 인덱스가 아니기 때문에.

In [59]:
s.loc[('m', 'a')]  #> 튜플 형태의 인덱스를 사용한 indexing.

np.int64(48)

In [60]:
s.loc[[('m', 'a'), ('f', 'a')]]

m  a    48
f  a     0
Name: score, dtype: int64

In [61]:
s_idx_sorted = s.sort_index()
s_idx_sorted

f  a     0
   b     7
   c    95
m  a    48
   b    77
   c    30
Name: score, dtype: int64

In [62]:
s_idx_sorted.loc['f':'m']
#> slicing은 인덱스들이 정렬된 상태일 때 가능.
#> 첫번째 계층(level)의 인덱스만으로도 slicing 가능.

f  a     0
   b     7
   c    95
m  a    48
   b    77
   c    30
Name: score, dtype: int64

In [64]:
s_idx_sorted.loc[('f', 'a'):('m', 'a')]  #> 튜플 형태의 인덱스로 slicing 가능.

f  a     0
   b     7
   c    95
m  a    48
Name: score, dtype: int64