<a href="https://colab.research.google.com/github/JakeOh/202511_BD53/blob/main/lab_python/da11_index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

# Series 인덱스

## 단일 계층 인덱스

In [44]:
s = pd.Series(data=np.random.rand(5), name='rand_num')
#> Series 객체도 (데이터프레임의 컬럼처럼) 값들의 이름을 설정할 수 있음.
s

0    0.798166
1    0.409831
2    0.574669
3    0.059200
4    0.086920
Name: rand_num, dtype: float64

In [45]:
s.index  #> Series 객체가 가지고 있는 index 속성

RangeIndex(start=0, stop=5, step=1)

In [46]:
s.values  #> Series 객체가 가지고 있는 values 속성 -> 값들을 아이템으로 갖는 1차원 ndarray(배열)

array([0.79816619, 0.40983127, 0.57466882, 0.05919979, 0.08692045])

In [47]:
s.loc[0]  #> 인덱스 0 위치의 값

np.float64(0.7981661880484631)

In [48]:
s.loc[[0, 4]]  #> 인덱스 0, 4 위치의 값들

0    0.798166
4    0.086920
Name: rand_num, dtype: float64

In [49]:
s = pd.Series(data=np.random.randint(100, size=5), name='score',
              index=['scott', 'allen', 'king', '홍길동', '오쌤'])
s

scott    28
allen    57
king     74
홍길동      60
오쌤       78
Name: score, dtype: int64

In [50]:
s.index

Index(['scott', 'allen', 'king', '홍길동', '오쌤'], dtype='object')

In [51]:
s.values

array([28, 57, 74, 60, 78])

In [52]:
s.index.nlevels  # 인덱스의 레벨(계층) 개수

1

In [53]:
s.loc['홍길동']  #> 해당 인덱스의 값 1개

np.int64(60)

In [54]:
s.loc[['scott', '홍길동']]  #> 해당 인덱스들의 값들

scott    28
홍길동      60
Name: score, dtype: int64

## 계층적 인덱스(hierachical index), multi-level index

In [55]:
s = pd.Series(data=np.random.randint(100, size=6), name='score',
              index=[['m', 'm', 'm', 'f', 'f', 'f'], ['a', 'b', 'c', 'a', 'b', 'c']])
s

m  a    48
   b    77
   c    30
f  a     0
   b     7
   c    95
Name: score, dtype: int64

In [56]:
s.values  #> 1차원 배열(ndarray)

array([48, 77, 30,  0,  7, 95])

In [57]:
s.index  #> MultiIndex - 튜플들을 아이템으로 갖는 배열

MultiIndex([('m', 'a'),
            ('m', 'b'),
            ('m', 'c'),
            ('f', 'a'),
            ('f', 'b'),
            ('f', 'c')],
           )

In [58]:
s.index.nlevels  #> 계층(level)들의 개수

2

In [38]:
s.iloc[-1]

np.int64(40)

### Multi-level index에서 indexing, slicing

nlevels(인덱스의 계층 개수)가 2개 이상인 multi-level 인덱스를 loc 속성에서 사용할 때,
*   첫번째 계층(level)의 인덱스만 가지고 indexing과 slicing을 할 수 있음.
*   두번째 계층의 인덱스만 가지고는 indexing/slicing을 할 수 없음!
*   튜플 형태의 인덱스로 indexing/slicing을 할 수 있음.


In [39]:
s

m  a    37
   b    95
   c    96
f  a    48
   b     3
   c    40
Name: score, dtype: int64

In [33]:
s.loc['m']  # 첫번째 계층(level)의 인덱스로  indexing.

a     5
b    98
c    72
Name: score, dtype: int64

In [41]:
s.loc['f']

a    48
b     3
c    40
Name: score, dtype: int64

In [ ]:
s.loc['a']  #> KeyError - 'a'는 첫번째 계층(level)의 인덱스가 아니기 때문에.

In [59]:
s.loc[('m', 'a')]  #> 튜플 형태의 인덱스를 사용한 indexing.

np.int64(48)

In [66]:
s.loc[[('m', 'a'), ('f', 'a')]]

m  a    48
f  a     0
Name: score, dtype: int64

In [61]:
s_idx_sorted = s.sort_index()
s_idx_sorted

f  a     0
   b     7
   c    95
m  a    48
   b    77
   c    30
Name: score, dtype: int64

In [62]:
s_idx_sorted.loc['f':'m']
#> slicing은 인덱스들이 정렬된 상태일 때 가능.
#> 첫번째 계층(level)의 인덱스만으로도 slicing 가능.

f  a     0
   b     7
   c    95
m  a    48
   b    77
   c    30
Name: score, dtype: int64

In [64]:
s_idx_sorted.loc[('f', 'a'):('m', 'a')]  #> 튜플 형태의 인덱스로 slicing 가능.

f  a     0
   b     7
   c    95
m  a    48
Name: score, dtype: int64


*   `pd.Series.sort_index()`: 인덱스를 정렬.
*   `pd.Series.sort_values()`: 값들을 정렬.
*   `inplace` 파라미터:
    *   `inplace=True`: 원본 Series를 정렬된 상태로 변경.
    *   `inplace=False`: 기본값. 원본은 수정되지 않고, 정렬된 새로운 Series 객체를 리턴.


In [82]:
np.random.seed(42)
s = pd.Series(data=np.random.rand(5), index=['b', 'a', 'z', 'd', 'c'])
s

b    0.374540
a    0.950714
z    0.731994
d    0.598658
c    0.156019
dtype: float64

In [83]:
s.sort_values()  #> inplace=False: 기본값

c    0.156019
b    0.374540
d    0.598658
z    0.731994
a    0.950714
dtype: float64

In [84]:
s  #> 원본 Series는 값들이 정렬되어 있지 않음.

b    0.374540
a    0.950714
z    0.731994
d    0.598658
c    0.156019
dtype: float64

In [85]:
s.sort_values(inplace=True)  #> inplace=True: 원본 변경. 리턴 값은 없음.

In [86]:
s  #> 원본 Series가 값들 오름차순 정렬된 상태.

c    0.156019
b    0.374540
d    0.598658
z    0.731994
a    0.950714
dtype: float64

In [87]:
s.sort_index()  #> inplace=False: 기본값. 인덱스들이 정렬된 Series를 리턴.

a    0.950714
b    0.374540
c    0.156019
d    0.598658
z    0.731994
dtype: float64

In [88]:
s  #> 원본은 변경 없음.

c    0.156019
b    0.374540
d    0.598658
z    0.731994
a    0.950714
dtype: float64

In [89]:
s.sort_index(inplace=True)  #> inplace=True: 원본 Series의 인덱스를 정렬. 리턴 값은 없음.

In [90]:
s

a    0.950714
b    0.374540
c    0.156019
d    0.598658
z    0.731994
dtype: float64

## index swapping

multi-level 인덱스에서 인덱스의 레벨을 바꿈.

In [91]:
np.random.seed(42)
s = pd.Series(data=np.random.randint(100, size=6),
              index=[['m'] * 3 + ['f'] * 3, ['a', 'b', 'c'] * 2])
s

m  a    51
   b    92
   c    14
f  a    71
   b    60
   c    20
dtype: int64

In [92]:
s.swaplevel()

a  m    51
b  m    92
c  m    14
a  f    71
b  f    60
c  f    20
dtype: int64

In [93]:
s

m  a    51
   b    92
   c    14
f  a    71
   b    60
   c    20
dtype: int64

In [96]:
# nlevels=3인 인덱스를 갖는 Series
np.random.seed(42)
s = pd.Series(data=np.random.rand(6),
              index=[np.arange(1, 7),
                     ['A'] * 3 + ['B'] * 3,
                     ['a', 'b', 'c'] * 2])
s

1  A  a    0.374540
2  A  b    0.950714
3  A  c    0.731994
4  B  a    0.598658
5  B  b    0.156019
6  B  c    0.155995
dtype: float64

In [97]:
s.swaplevel()  # i=-2, j=-1: 기본값. 끝에서 두번째 인덱스와 마지막 인덱스를 서로 바꿈.

1  a  A    0.374540
2  b  A    0.950714
3  c  A    0.731994
4  a  B    0.598658
5  b  B    0.156019
6  c  B    0.155995
dtype: float64

In [99]:
s.swaplevel(i=0, j=1)  #> 첫번째 인덱스와 두번째 인덱스를 바꿈.

A  1  a    0.374540
   2  b    0.950714
   3  c    0.731994
B  4  a    0.598658
   5  b    0.156019
   6  c    0.155995
dtype: float64

# DataFrame 인덱스

In [102]:
np.random.seed(42)
df = pd.DataFrame(data=np.random.randint(100, size=(6, 3)),
                  columns=['total_bill', 'tip', 'size'],
                  index=[['Fri', 'Fri', 'Sat', 'Sat', 'Sun', 'Sun'],
                         ['Lunch', 'Dinner'] * 3])
df

total_bill  tip  size
Fri Lunch           51   92    14
    Dinner          71   60    20
Sat Lunch           82   86    74
    Dinner          74   87    99
Sun Lunch           23    2    21
    Dinner          52    1    87

In [103]:
df.values  #> DataFrame의 값들로 이루어진 2차원 배열(ndarray)

array([[51, 92, 14],
       [71, 60, 20],
       [82, 86, 74],
       [74, 87, 99],
       [23,  2, 21],
       [52,  1, 87]])

In [104]:
df.columns  #> 컬럼 이름(인덱스)들로 이루어진 배열

Index(['total_bill', 'tip', 'size'], dtype='object')

In [105]:
df.index  #> multi-level 인덱스: 튜플들의 배열

MultiIndex([('Fri',  'Lunch'),
            ('Fri', 'Dinner'),
            ('Sat',  'Lunch'),
            ('Sat', 'Dinner'),
            ('Sun',  'Lunch'),
            ('Sun', 'Dinner')],
           )

In [106]:
df.loc['Fri']  # 첫번째 인덱스만 가지고도 indexing

total_bill  tip  size
Lunch           51   92    14
Dinner          71   60    20

In [107]:
df.loc[('Fri', 'Dinner')]  # 첫번째, 두번째 계층의 인덱스들을 모두 사용한 indexing

total_bill    71
tip           60
size          20
Name: (Fri, Dinner), dtype: int64

In [108]:
df.loc[['Sat', 'Sun']]

total_bill  tip  size
Sat Lunch           82   86    74
    Dinner          74   87    99
Sun Lunch           23    2    21
    Dinner          52    1    87

In [109]:
df.loc[[('Fri', 'Lunch'), ('Sat', 'Lunch'), ('Sun', 'Lunch')]]

total_bill  tip  size
Fri Lunch          51   92    14
Sat Lunch          82   86    74
Sun Lunch          23    2    21

In [ ]:
df.loc['Lunch']  #> KeyError - 'Lunch'는 첫번째 계층(level)의 인덱스가 아니기 때문에.

In [111]:
df.loc['Fri':'Sat']

total_bill  tip  size
Fri Lunch           51   92    14
    Dinner          71   60    20
Sat Lunch           82   86    74
    Dinner          74   87    99

In [113]:
df.index.nlevels

2

In [114]:
df.swaplevel()  # i=-2, j=-1: 기본값. 끝에서 두번째 인덱스와 마지막 인덱스를 서로 바꿈.

total_bill  tip  size
Lunch  Fri          51   92    14
Dinner Fri          71   60    20
Lunch  Sat          82   86    74
Dinner Sat          74   87    99
Lunch  Sun          23    2    21
Dinner Sun          52    1    87

In [118]:
df.swaplevel().loc['Lunch']

total_bill  tip  size
Fri          51   92    14
Sat          82   86    74
Sun          23    2    21

## DataFrame 컬럼 <---> DataFrame 인덱스

*   `pd.DataFrame.set_index()`: 데이터프레임의 컬럼(들)을 인덱스로 변환.
*   `pd.DataFrame.reset_index()`: 인덱스를 데이터프레임의 컬럼으로 변환.


In [119]:
df

total_bill  tip  size
Fri Lunch           51   92    14
    Dinner          71   60    20
Sat Lunch           82   86    74
    Dinner          74   87    99
Sun Lunch           23    2    21
    Dinner          52    1    87

## `reset_index`

In [120]:
df.reset_index()  # 기본 동작: 모든 level의 인덱스를 컬럼으로 변환.

level_0 level_1  total_bill  tip  size
0     Fri   Lunch          51   92    14
1     Fri  Dinner          71   60    20
2     Sat   Lunch          82   86    74
3     Sat  Dinner          74   87    99
4     Sun   Lunch          23    2    21
5     Sun  Dinner          52    1    87

In [122]:
# 인덱스를 컬럼으로 변환할 때 사용할 컬럼 이름들을 설정.
df.reset_index(names=['day', 'time'])

day    time  total_bill  tip  size
0  Fri   Lunch          51   92    14
1  Fri  Dinner          71   60    20
2  Sat   Lunch          82   86    74
3  Sat  Dinner          74   87    99
4  Sun   Lunch          23    2    21
5  Sun  Dinner          52    1    87

In [123]:
df

total_bill  tip  size
Fri Lunch           51   92    14
    Dinner          71   60    20
Sat Lunch           82   86    74
    Dinner          74   87    99
Sun Lunch           23    2    21
    Dinner          52    1    87

In [126]:
df.reset_index(level=0, names='day')

day  total_bill  tip  size
Lunch   Fri          51   92    14
Dinner  Fri          71   60    20
Lunch   Sat          82   86    74
Dinner  Sat          74   87    99
Lunch   Sun          23    2    21
Dinner  Sun          52    1    87

In [135]:
df.reset_index(level=-1, names=['day', 'time'])

time  total_bill  tip  size
Fri   Lunch          51   92    14
Fri  Dinner          71   60    20
Sat   Lunch          82   86    74
Sat  Dinner          74   87    99
Sun   Lunch          23    2    21
Sun  Dinner          52    1    87

## `set_index`

In [136]:
exam = pd.DataFrame(data={
    'class': [1] * 5 + [2] * 5,
    'id': np.arange(1, 11),
    'math': np.random.randint(100, size=10),
    'science': np.random.randint(100, size=10)
})
exam

class  id  math  science
0      1   1    29       88
1      1   2    37       48
2      1   3     1       90
3      1   4    63       58
4      1   5    59       41
5      2   6    20       91
6      2   7    32       59
7      2   8    75       79
8      2   9    57       14
9      2  10    21       61

In [137]:
# class = 1 인 데이터 선택
exam[exam['class'] == 1]

class  id  math  science
0      1   1    29       88
1      1   2    37       48
2      1   3     1       90
3      1   4    63       58
4      1   5    59       41

In [138]:
exam_cls = exam.set_index(keys=['class'])
exam_cls

id  math  science
class                   
1       1    29       88
1       2    37       48
1       3     1       90
1       4    63       58
1       5    59       41
2       6    20       91
2       7    32       59
2       8    75       79
2       9    57       14
2      10    21       61

In [139]:
exam_cls.loc[1]

id  math  science
class                   
1       1    29       88
1       2    37       48
1       3     1       90
1       4    63       58
1       5    59       41

In [141]:
exam.set_index(keys=['class', 'id'])

math  science
class id               
1     1     29       88
      2     37       48
      3      1       90
      4     63       58
      5     59       41
2     6     20       91
      7     32       59
      8     75       79
      9     57       14
      10    21       61

In [143]:
exam.set_index(keys=['id', 'class'])

math  science
id class               
1  1        29       88
2  1        37       48
3  1         1       90
4  1        63       58
5  1        59       41
6  2        20       91
7  2        32       59
8  2        75       79
9  2        57       14
10 2        21       61