<a href="https://colab.research.google.com/github/JakeOh/202511_BD53/blob/main/lab_ml/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

In [1]:
import numpy as np

# `numpy.ndarray` 클래스 속성들(properties)

In [2]:
# 2차원 배열(2-dimensional array)
arr = np.ones(shape=(2, 3))  #> 모든 원소가 1인 배열

In [3]:
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
arr.shape  # shape 속성: 배열의 각 축(axis)을 따라서 있는 원소 개수들의 튜플(tuple)

(2, 3)

In [5]:
arr.size  # size 속성: 배열의 모든 원소 개수

6

In [6]:
arr.ndim  # ndim 속성: 배열의 차원 개수. 축(axis)의 개수.

2

In [7]:
arr.dtype  # dtype 속성: 배열 원소의 데이터 타입(data type)

dtype('float64')

In [8]:
# 1차원 배열(1-dimensional array)
arr = np.arange(10)
print(arr)
print('shape:', arr.shape)
print('size:', arr.size)
print('ndim:', arr.ndim)
print('dtype:', arr.dtype)

[0 1 2 3 4 5 6 7 8 9]
shape: (10,)
size: 10
ndim: 1
dtype: int64


In [9]:
# 3차원 배열(3-dimensional array)
arr = np.arange(1, 25).reshape((2, 3, 4))
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [10]:
print('shape:', arr.shape)
print('size:', arr.size)
print('ndim:', arr.ndim)
print('dtype:', arr.dtype)

shape: (2, 3, 4)
size: 24
ndim: 3
dtype: int64


# Indexing

인덱스를 사용해서 배열 원소를 참조.

In [11]:
print(arr)  #> 3d array

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [12]:
print(arr[0])  # 2d array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
print(arr[0][0])  # 1d array

[1 2 3 4]


In [14]:
print(arr[0, 0])

[1 2 3 4]


In [15]:
print(arr[0][0][0])  #> 값(int) --> scalar

1


In [16]:
print(arr[0, 0, 0])

1


*   Python list 인덱스 사용 방법:
    *   `list[i][j][k]...`
*   NumPy ndarray 인덱스 사용 방법:
    *   `array[i][j][k]...`
    *   `array[i, j, k, ...]`

# Slicing

배열을 잘라서 새로운 배열을 만듦.

## 1d array의 slicing

In [17]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
print(arr[1:5])

[1 2 3 4]


In [19]:
print(arr[:3])  # 시작 인덱스 0은 생략 가능

[0 1 2]


In [20]:
print(arr[-3:])  # 배열의 끝까지 자를 때는 마지막 인덱스를 생략할 수 있음.

[7 8 9]


In [21]:
print(arr[0:1])  #> slicing --> 배열(ndarray)
print(arr[0])  #> indexing --> 배열의 원소

[0]
0


## 2d array의 slicing

In [22]:
arr = np.arange(1, 21).reshape((4, 5))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [23]:
print(arr[:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [24]:
print(arr[:2, :])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [25]:
print(arr[:2, :3])

[[1 2 3]
 [6 7 8]]


In [26]:
print(arr[1:3, 1:4])

[[ 7  8  9]
 [12 13 14]]


In [27]:
print(arr[:3, :2])

[[ 1  2]
 [ 6  7]
 [11 12]]


In [28]:
print(arr[:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [29]:
print(arr[:3][:2])  # arr[:3, :2]의 결과와 다름!

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## 3d array의 slicing

In [30]:
arr = np.arange(60).reshape((3, 4, 5))
print(arr)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [31]:
print(arr[:2])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [32]:
print(arr[:2, :, :])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [33]:
print(arr[:2, :2])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [34]:
print(arr[:2, :2, :])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [35]:
print(arr[:2, :2, :2])

[[[ 0  1]
  [ 5  6]]

 [[20 21]
  [25 26]]]


In [36]:
print(arr[:1, :, :])  #> 3d array

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]]


In [37]:
print(arr[0, :, :])  #> 2d array. arr[:1, :, :]와 다름!

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


# 배열 모양(shape) 변경

*   `reshape()`
*   `ravel()`
*   `flatten()`
*   `np.newaxis` 속성


## reshape

In [38]:
arr_1d = np.arange(12)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [39]:
# arr_1d를 (4, 3) shape의 2d array로 변환
arr_2d = arr_1d.reshape((4, 3))
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [40]:
# reshape 메서드에 아규먼트를 전달할 때, 자동으로 계산할 수 있는 차원의 값은 -1을 사용할 수 있음.
arr_2d = arr_1d.reshape((4, -1))  # (4, 3)
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [41]:
arr_2d = arr_1d.reshape((-1, 4))  # (3, 4)
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [42]:
arr_1d = np.arange(24)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [43]:
# arr_1d를 (2, 3, 4) 모양의 3d array로 변환
arr_3d = arr_1d.reshape((2, 3, 4))
print(arr_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [44]:
arr_3d = arr_1d.reshape((2, 3, -1))
print(arr_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [45]:
arr_3d = arr_1d.reshape((-1, 3, 4))
print(arr_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## ravel vs flatten

*   ravel
    *   n차원 배열을 1차원 배열로 변환한 "뷰(view)"를 리턴.
    *   새로운 1차원 배열을 만드는 것이 아니라, 원본 배열의 모양을 1차원처럼 보여줄 뿐.
    *   리턴된 1차원 배열에서 원소를 변경하면, 원본 배열도 변경됨!
*   flatten
    *   n차원 배열을 1차원 배열로 변환한 "복사본(copy)"을 리턴.
    *   원본 배열과는 별개의 새로운 1차원 배열을 메모리에 만들어서 리턴.
    *   리턴된 1차원 배열의 원소를 변경하는 것은 원본 배열에 영향을 주지 않음!


In [46]:
arr_2d = np.arange(12).reshape((3, 4))
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [47]:
flattened = arr_2d.flatten()  # 2d --> 1d
print(flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [48]:
flattened[0] = 123
print(flattened)

[123   1   2   3   4   5   6   7   8   9  10  11]


In [49]:
print(arr_2d)  # 원본 2d array은 변경되지 않음.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [50]:
raveled = arr_2d.ravel()  # 2d --> 1d
print(raveled)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [51]:
raveled[0] = 123
print(raveled)

[123   1   2   3   4   5   6   7   8   9  10  11]


In [52]:
print(arr_2d)  # 원본 2d array이 변경됨!

[[123   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


## `np.newaxis` 속성을 사용한 차원 늘리기

In [53]:
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [54]:
arr.shape

(6,)

In [55]:
result = arr[np.newaxis, :]
print(result)

[[0 1 2 3 4 5]]


In [56]:
result.shape

(1, 6)

In [57]:
print(arr.reshape((1, -1)))

[[0 1 2 3 4 5]]


In [58]:
result = arr[:, np.newaxis]
print(result)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [59]:
result.shape

(6, 1)

In [60]:
print(arr.reshape((-1, 1)))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


# 배열 합치기(concatenate)

*   `np.concatenate([array1, array2, ...], axis=0)`: 특정 축(axis) 방향으로 배열 이어붙이기.
*   `np.r_[array1, array2]`: 행들을 이어붙이기. axis=0 방향으로 이어붙이기.
*   `np.c_[array1, array2]`: 컬럼들을 이어붙이기. axis=1 방향으로 이어붙이기.


In [61]:
# (2, 3) shape의 2d array
arr1 = np.arange(6).reshape((2, 3))
print(arr1)

[[0 1 2]
 [3 4 5]]


In [62]:
# (1, 3) shape의 2d array
arr2 = np.array([[10, 20, 30]])
print(arr2)

[[10 20 30]]


In [63]:
# (2, 1) shape의 2d array
arr3 = np.array([[11], [12]])
print(arr3)

[[11]
 [12]]


In [64]:
result = np.concatenate([arr1, arr2])  # axis=0(기본값) 생략 가능
print(result)

[[ 0  1  2]
 [ 3  4  5]
 [10 20 30]]


In [65]:
result = np.concatenate([arr1, arr3], axis=1)
print(result)

[[ 0  1  2 11]
 [ 3  4  5 12]]


In [66]:
np.r_[arr1, arr2]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 20, 30]])

In [67]:
np.c_[arr1, arr3]

array([[ 0,  1,  2, 11],
       [ 3,  4,  5, 12]])

In [68]:
arr1 = np.arange(6).reshape((2, 3))
print(arr1)

[[0 1 2]
 [3 4 5]]


In [69]:
arr2 = np.array([10, 20, 30])
print(arr2)

[10 20 30]


In [70]:
# np.concatenate([arr1, arr2], axis=0)
#> ValueError 발생. 차원이 다르면 이어붙이기가 되지 않음.

# Broadcasting

*   numpy.ndarray의 연산(+, -, *, /, ==, !=, >, <, ...)은 같은 인덱스(위치)의 원소들(element-wise)끼리 연산이 수행됨.
*   서로 모양(shape)이 다른 배열끼리도 element-wise 연산이 가능한 경우가 있음 --> broadcast
*   broadcasting이 가능한 경우
    *   누락되었거나 길이가 1인 차원에 대해서 broadcasting이 수행.
    *   이어지는 차원의 축의 길이가 같은 경우에 broadcasting이 가능.

## ndarray와 scalar의 연산

항상 연산이 가능(항상 브로드캐스트가 가능). 스칼라를 배열의 각 원소마다 연산 수행.

In [71]:
a = np.array([1, 2, 3])
print(a)
print(a + 10)

[1 2 3]
[11 12 13]


## 2d array와 2d array의 broadcast

In [72]:
a = np.arange(1, 7).reshape((2, 3))  # shape: (2, 3)
print(a)

[[1 2 3]
 [4 5 6]]


In [73]:
b = np.array([[7, 8, 9]])  # shape: (1, 3)
print(b)

[[7 8 9]]


In [74]:
print(a + b)

[[ 8 10 12]
 [11 13 15]]


In [75]:
c = np.array([[11], [12]])  # shape: (2, 1)
print(c)

[[11]
 [12]]


In [76]:
print(a + c)

[[12 13 14]
 [16 17 18]]


## 2d array와 1d array의 broadcast

In [77]:
print(a)

[[1 2 3]
 [4 5 6]]


In [78]:
d = np.array([7, 8, 9])  # shape: (3,)
print(d)

[7 8 9]


In [79]:
print(a + b)

[[ 8 10 12]
 [11 13 15]]


In [80]:
e = np.array([7, 8])  # shape: (2,)
print(e)

[7 8]


In [ ]:
# print(a + e)
#> ValueError 발생: (2, 3)과 (2,) 모양의 배열들은 브로드캐스트가 불가능.