<a href="https://colab.research.google.com/github/JakeOh/202511_BD53/blob/main/lab_ml/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

In [1]:
import numpy as np

# `numpy.ndarray` 클래스 속성들(properties)

In [2]:
# 2차원 배열(2-dimensional array)
arr = np.ones(shape=(2, 3))  #> 모든 원소가 1인 배열

In [3]:
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
arr.shape  # shape 속성: 배열의 각 축(axis)을 따라서 있는 원소 개수들의 튜플(tuple)

(2, 3)

In [7]:
arr.size  # size 속성: 배열의 모든 원소 개수

6

In [8]:
arr.ndim  # ndim 속성: 배열의 차원 개수. 축(axis)의 개수.

2

In [9]:
arr.dtype  # dtype 속성: 배열 원소의 데이터 타입(data type)

dtype('float64')

In [11]:
# 1차원 배열(1-dimensional array)
arr = np.arange(10)
print(arr)
print('shape:', arr.shape)
print('size:', arr.size)
print('ndim:', arr.ndim)
print('dtype:', arr.dtype)

[0 1 2 3 4 5 6 7 8 9]
shape: (10,)
size: 10
ndim: 1
dtype: int64


In [12]:
# 3차원 배열(3-dimensional array)
arr = np.arange(1, 25).reshape((2, 3, 4))
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [14]:
print('shape:', arr.shape)
print('size:', arr.size)
print('ndim:', arr.ndim)
print('dtype:', arr.dtype)

shape: (2, 3, 4)
size: 24
ndim: 3
dtype: int64


# Indexing

인덱스를 사용해서 배열 원소를 참조.

In [15]:
print(arr)  #> 3d array

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [16]:
print(arr[0])  # 2d array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
print(arr[0][0])  # 1d array

[1 2 3 4]


In [18]:
print(arr[0, 0])

[1 2 3 4]


In [19]:
print(arr[0][0][0])  #> 값(int) --> scalar

1


In [20]:
print(arr[0, 0, 0])

1


*   Python list 인덱스 사용 방법:
    *   `list[i][j][k]...`
*   NumPy ndarray 인덱스 사용 방법:
    *   `array[i][j][k]...`
    *   `array[i, j, k, ...]`