<a href="https://colab.research.google.com/github/JakeOh/202511_BD53/blob/main/lab_ml/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

In [1]:
import numpy as np

# `numpy.ndarray` 클래스 속성들(properties)

In [2]:
# 2차원 배열(2-dimensional array)
arr = np.ones(shape=(2, 3))  #> 모든 원소가 1인 배열

In [3]:
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
arr.shape  # shape 속성: 배열의 각 축(axis)을 따라서 있는 원소 개수들의 튜플(tuple)

(2, 3)

In [7]:
arr.size  # size 속성: 배열의 모든 원소 개수

6

In [8]:
arr.ndim  # ndim 속성: 배열의 차원 개수. 축(axis)의 개수.

2

In [9]:
arr.dtype  # dtype 속성: 배열 원소의 데이터 타입(data type)

dtype('float64')

In [11]:
# 1차원 배열(1-dimensional array)
arr = np.arange(10)
print(arr)
print('shape:', arr.shape)
print('size:', arr.size)
print('ndim:', arr.ndim)
print('dtype:', arr.dtype)

[0 1 2 3 4 5 6 7 8 9]
shape: (10,)
size: 10
ndim: 1
dtype: int64


In [12]:
# 3차원 배열(3-dimensional array)
arr = np.arange(1, 25).reshape((2, 3, 4))
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [14]:
print('shape:', arr.shape)
print('size:', arr.size)
print('ndim:', arr.ndim)
print('dtype:', arr.dtype)

shape: (2, 3, 4)
size: 24
ndim: 3
dtype: int64


# Indexing

인덱스를 사용해서 배열 원소를 참조.

In [15]:
print(arr)  #> 3d array

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [16]:
print(arr[0])  # 2d array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
print(arr[0][0])  # 1d array

[1 2 3 4]


In [18]:
print(arr[0, 0])

[1 2 3 4]


In [19]:
print(arr[0][0][0])  #> 값(int) --> scalar

1


In [20]:
print(arr[0, 0, 0])

1


*   Python list 인덱스 사용 방법:
    *   `list[i][j][k]...`
*   NumPy ndarray 인덱스 사용 방법:
    *   `array[i][j][k]...`
    *   `array[i, j, k, ...]`

# Slicing

배열을 잘라서 새로운 배열을 만듦.

## 1d array의 slicing

In [21]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
print(arr[1:5])

[1 2 3 4]


In [23]:
print(arr[:3])  # 시작 인덱스 0은 생략 가능

[0 1 2]


In [24]:
print(arr[-3:])  # 배열의 끝까지 자를 때는 마지막 인덱스를 생략할 수 있음.

[7 8 9]


In [25]:
print(arr[0:1])  #> slicing --> 배열(ndarray)
print(arr[0])  #> indexing --> 배열의 원소

[0]
0


## 2d array의 slicing

In [26]:
arr = np.arange(1, 21).reshape((4, 5))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [27]:
print(arr[:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [28]:
print(arr[:2, :])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [29]:
print(arr[:2, :3])

[[1 2 3]
 [6 7 8]]


In [30]:
print(arr[1:3, 1:4])

[[ 7  8  9]
 [12 13 14]]


In [36]:
print(arr[:3, :2])

[[ 1  2]
 [ 6  7]
 [11 12]]


In [34]:
print(arr[:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [35]:
print(arr[:3][:2])  # arr[:3, :2]의 결과와 다름!

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## 3d array의 slicing

In [37]:
arr = np.arange(60).reshape((3, 4, 5))
print(arr)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [38]:
print(arr[:2])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [39]:
print(arr[:2, :, :])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


In [40]:
print(arr[:2, :2])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [41]:
print(arr[:2, :2, :])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [42]:
print(arr[:2, :2, :2])

[[[ 0  1]
  [ 5  6]]

 [[20 21]
  [25 26]]]


In [46]:
print(arr[:1, :, :])  #> 3d array

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]]


In [45]:
print(arr[0, :, :])  #> 2d array. arr[:1, :, :]와 다름!

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


# 배열 모양(shape) 변경

*   `reshape()`
*   `ravel()`
*   `flatten()`
*   `np.newaxis` 속성


## reshape

In [47]:
arr_1d = np.arange(12)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [48]:
# arr_1d를 (4, 3) shape의 2d array로 변환
arr_2d = arr_1d.reshape((4, 3))
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [49]:
# reshape 메서드에 아규먼트를 전달할 때, 자동으로 계산할 수 있는 차원의 값은 -1을 사용할 수 있음.
arr_2d = arr_1d.reshape((4, -1))  # (4, 3)
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [50]:
arr_2d = arr_1d.reshape((-1, 4))  # (3, 4)
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [51]:
arr_1d = np.arange(24)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [52]:
# arr_1d를 (2, 3, 4) 모양의 3d array로 변환
arr_3d = arr_1d.reshape((2, 3, 4))
print(arr_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [53]:
arr_3d = arr_1d.reshape((2, 3, -1))
print(arr_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [54]:
arr_3d = arr_1d.reshape((-1, 3, 4))
print(arr_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## ravel vs flatten

*   ravel
    *   n차원 배열을 1차원 배열로 변환한 "뷰(view)"를 리턴.
    *   새로운 1차원 배열을 만드는 것이 아니라, 원본 배열의 모양을 1차원처럼 보여줄 뿐.
    *   리턴된 1차원 배열에서 원소를 변경하면, 원본 배열도 변경됨!
*   flatten
    *   n차원 배열을 1차원 배열로 변환한 "복사본(copy)"을 리턴.
    *   원본 배열과는 별개의 새로운 1차원 배열을 메모리에 만들어서 리턴.
    *   리턴된 1차원 배열의 원소를 변경하는 것은 원본 배열에 영향을 주지 않음!


In [55]:
arr_2d = np.arange(12).reshape((3, 4))
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [56]:
flattened = arr_2d.flatten()  # 2d --> 1d
print(flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [58]:
flattened[0] = 123
print(flattened)

[123   1   2   3   4   5   6   7   8   9  10  11]


In [59]:
print(arr_2d)  # 원본 2d array은 변경되지 않음.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [60]:
raveled = arr_2d.ravel()  # 2d --> 1d
print(raveled)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [62]:
raveled[0] = 123
print(raveled)

[123   1   2   3   4   5   6   7   8   9  10  11]


In [63]:
print(arr_2d)  # 원본 2d array이 변경됨!

[[123   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


## `np.newaxis` 속성을 사용한 차원 늘리기

In [64]:
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [65]:
arr.shape

(6,)

In [66]:
result = arr[np.newaxis, :]
print(result)

[[0 1 2 3 4 5]]


In [67]:
result.shape

(1, 6)

In [71]:
print(arr.reshape((1, -1)))

[[0 1 2 3 4 5]]


In [68]:
result = arr[:, np.newaxis]
print(result)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [69]:
result.shape

(6, 1)

In [72]:
print(arr.reshape((-1, 1)))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
