<a href="https://colab.research.google.com/github/JakeOh/202511_BD53/blob/main/lab_ml/ml16_ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ANN(Artificial Neural Network, 인공신경망)

# Imports

In [1]:
from sklearn import datasets
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score

import tensorflow as tf
import keras

In [2]:
tf.__version__

'2.19.0'

In [3]:
keras.__version__

'3.13.2'

# Iris 데이터셋

In [4]:
data, target = datasets.load_iris(return_X_y=True)

In [5]:
data.shape

(150, 4)

In [6]:
target.shape

(150,)

In [7]:
data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [11]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# 이진 분류(binary classification)

*   2개의 특성만을 사용
*   0(setosa)과 0이 아닌(versicolor, virginica) 클래스로 분류

In [9]:
x = data[:, :2]

In [10]:
x[:5]

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6]])

In [13]:
y = (target != 0).astype('int')
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# SGD Classifier(확률적 경사하강법 분류기)

In [14]:
# loss='log_loss': logistic 손실 함수를 최소화하는 확률적 경사 하강법. 확률 -> 분류.
# max_iter=10: epoch(모든 샘플을 사용해서 경사하강법을 수행) 횟수를 10번.
sgd = SGDClassifier(loss='log_loss', max_iter=10, n_jobs=-1, random_state=42)

In [15]:
sgd.fit(X=x, y=y)  # 모델 훈련 -> 손실함수를 최소로 만드는 가중치(절편과 계수들) 찾음.

SGDClassifier(loss='log_loss', max_iter=10, n_jobs=-1, random_state=42)

In [16]:
sgd.coef_

array([[ 107.47482122, -163.79917975]])

In [17]:
sgd.intercept_

array([-53.41269101])

$
z = -53 + 107 x_1 - 163 x_2
$

In [18]:
# SGD의 예측 확률
y_prob = sgd.predict_proba(X=x)

In [19]:
y_prob[:5]

array([[1.00000000e+00, 7.40567283e-35],
       [9.99999987e-01, 1.26753544e-08],
       [1.00000000e+00, 3.47056174e-32],
       [1.00000000e+00, 9.69472704e-30],
       [1.00000000e+00, 1.22541827e-46]])

In [20]:
y_prob[-5:]

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [21]:
# SGD 모델의 예측값
y_pred = sgd.predict(X=x)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [22]:
# SGD 모델의 정확도
accuracy_score(y_true=y, y_pred=y_pred)

0.9933333333333333

In [24]:
149/150

0.9933333333333333

# 신경망(Neural Network)

In [32]:
# 입력층(input layer)
inputs = keras.Input(shape=(2,))

In [33]:
# 출력층(output layer)
dense = keras.layers.Dense(units=1, activation='sigmoid')

In [34]:
# 신경망 모델 생성
model = keras.Sequential(layers=[inputs, dense])

In [35]:
# 생성된 신경망 모델 정보 요약
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3 (12.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

In [36]:
# 신경망 모델 컴파일: optimizer(최적화 알고리즘), loss(손실함수), metrics(평가 기준)을 설정
model.compile(optimizer=keras.optimizers.SGD(),
              loss=keras.losses.binary_crossentropy,
              metrics=[keras.metrics.binary_accuracy])

In [37]:
# 신경망 모델 훈련
model.fit(x=x, y=y, batch_size=1, epochs=10)

Epoch 1/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - binary_accuracy: 0.7200 - loss: 0.5535
Epoch 2/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8533 - loss: 0.4074
Epoch 3/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9200 - loss: 0.3675
Epoch 4/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9200 - loss: 0.3449
Epoch 5/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9267 - loss: 0.3205
Epoch 6/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9400 - loss: 0.2956
Epoch 7/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9600 - loss: 0.2760
Epoch 8/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9600 - loss: 0.2607
Epoch 9/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9600 - loss: 0.2437
Epoch 10/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9733 - loss: 0.2375


In [38]:
# 신경망 모델이 학습을 통해서 찾은 모델 파라미터들(가중치, weights)
model.weights

[<Variable path=sequential_1/dense_1/kernel, shape=(2, 1), dtype=float32, value=[[ 1.3862389]
  [-2.2164092]]>,
 <Variable path=sequential_1/dense_1/bias, shape=(1,), dtype=float32, value=[-0.11248186]>]

In [40]:
# 신경망 모델의 예측값
y_pred = model.predict(x=x)
y_pred.shape  #> (n_samples, 1): 150개 샘플들의 양성(1)일 예측 확률

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step 


(150, 1)

In [41]:
y_pred[:5]

array([[0.31000516],
       [0.5077148 ],
       [0.33410668],
       [0.3528236 ],
       [0.23860182]], dtype=float32)

In [42]:
y_pred[-5:]

array([[0.9259508],
       [0.9560518],
       [0.9045508],
       [0.7203921],
       [0.8048835]], dtype=float32)

In [43]:
y_pred_label = (y_pred > 0.5).astype('int').ravel()
y_pred_label

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [44]:
# 신경망 모델 평가
model.evaluate(x=x, y=y)  #> [loss, accuracry]

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.9800 - loss: 0.2259  


[0.2259184718132019, 0.9800000190734863]

# 은닉층(hidden layer)을 가지고 있는 신경망

In [45]:
inputs = keras.layers.Input(shape=(2,))  # 입력층
dense1 = keras.layers.Dense(units=2, activation='sigmoid')  # 은닉층
dense2 = keras.layers.Dense(units=1, activation='sigmoid')  # 출력층

In [46]:
model = keras.Sequential(layers=[inputs, dense1, dense2])  # 신경망

In [47]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [48]:
# 모델 컴파일: 어떤 손실함수를 어떤 평가 기준으로 어떻게 최적화할 것인가를 설정
model.compile(optimizer=keras.optimizers.SGD(),
              loss=keras.losses.binary_crossentropy,
              metrics=[keras.metrics.binary_accuracy])

In [58]:
# 모델 훈련
model.fit(x=x, y=y, batch_size=30, epochs=10)

Epoch 1/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.7467 - loss: 0.4892 
Epoch 2/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.7467 - loss: 0.4888 
Epoch 3/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.7467 - loss: 0.4884 
Epoch 4/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.7467 - loss: 0.4877 
Epoch 5/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.7533 - loss: 0.4873 
Epoch 6/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - binary_accuracy: 0.7533 - loss: 0.4869 
Epoch 7/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.7533 - loss: 0.4864 
Epoch 8/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.7533 - loss: 0.4860 
Epoch 9/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.7533 - loss: 0.4855 
Epoch 10/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - binary_accuracy: 0.7533 - loss: 0.4852 


In [50]:
model.weights

[<Variable path=sequential_2/dense_2/kernel, shape=(2, 2), dtype=float32, value=[[-1.0836427  -0.30083776]
  [ 0.6807336   0.09934825]]>,
 <Variable path=sequential_2/dense_2/bias, shape=(2,), dtype=float32, value=[-0.03434636 -0.01563191]>,
 <Variable path=sequential_2/dense_3/kernel, shape=(2, 1), dtype=float32, value=[[ 0.16914698]
  [-0.39587596]]>,
 <Variable path=sequential_2/dense_3/bias, shape=(1,), dtype=float32, value=[0.73211575]>]

In [56]:
model.evaluate(x=x, y=y)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - binary_accuracy: 0.6933 - loss: 0.5030  


[0.502950131893158, 0.6933333277702332]

# SGD

4개의 특성을 모두 사용한 다중 클래스(0/1/2) 분류

In [59]:
sgd = SGDClassifier(loss='log_loss', n_jobs=-1, random_state=42)  # max_iter=1000

In [60]:
# data: (150, 4), target: (150,)
sgd.fit(X=data, y=target)  # 모델 훈련

SGDClassifier(loss='log_loss', n_jobs=-1, random_state=42)

In [61]:
sgd.coef_  #> (3, 4)

array([[   7.32064421,   13.17715959,  -27.57442655,  -12.68911664],
       [  36.72801312,  -95.62396704,   33.04272408,  -96.76701144],
       [-123.44647495, -105.30456435,  149.42075067,  157.58173689]])

In [62]:
sgd.intercept_  #> (3,)

array([   4.97012943,  128.91629652, -130.52603923])

In [63]:
y_prob = sgd.predict_proba(X=data)

In [64]:
y_prob.shape  #> (150, 3)

(150, 3)

In [65]:
y_prob[:5]

array([[0.50005338, 0.49994662, 0.        ],
       [0.5       , 0.5       , 0.        ],
       [0.5       , 0.5       , 0.        ],
       [0.5       , 0.5       , 0.        ],
       [0.9917711 , 0.0082289 , 0.        ]])

In [66]:
y_pred = sgd.predict(X=data)

In [67]:
y_pred[:5]

array([0, 1, 0, 0, 0])

In [68]:
accuracy_score(y_true=target, y_pred=y_pred)

0.62

# 신경망

4개 특성을 모두 사용한 다중 클래스(0/1/2) 분류

In [69]:
model = keras.Sequential()  # Sequential(완전 연결 신경망) 객체 생성

In [70]:
# 신경망에 입력층을 추가
model.add(keras.layers.Input(shape=(4,)))

In [71]:
# 신경망에 출력층을 추가
model.add(keras.layers.Dense(units=3, activation='softmax'))

In [72]:
model.summary()
#> # of params = 4 features x 3 units + 3 bias = 15

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 15 (60.00 B)

 Trainable params: 15 (60.00 B)

 Non-trainable params: 0 (0.00 B)

In [73]:
# 모델 컴파일
model.compile(optimizer=keras.optimizers.SGD(),
              loss=keras.losses.sparse_categorical_crossentropy,
              metrics=[keras.metrics.sparse_categorical_accuracy])

In [74]:
# 모델 훈련
model.fit(x=data, y=target, epochs=10)

Epoch 1/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.1469 - sparse_categorical_accuracy: 0.3333  
Epoch 2/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.3495 - sparse_categorical_accuracy: 0.3333 
Epoch 3/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.8472 - sparse_categorical_accuracy: 0.5733
Epoch 4/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7530 - sparse_categorical_accuracy: 0.8000
Epoch 5/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.7251 - sparse_categorical_accuracy: 0.8067
Epoch 6/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7112 - sparse_categorical_accuracy: 0.8200 
Epoch 7/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7029 - sparse_categorical_accuracy: 0.7867 
Epoch 8/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6930 - sparse_categorical_accuracy: 0.7667
Epoch 9/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.6806 - sparse_categorical_accuracy: 0.8200 
Epoch 10/10
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6705 - sparse_categor

In [75]:
model.weights
#> kernel: (4, 3)
#> bias: (3,)

[<Variable path=sequential_3/dense_4/kernel, shape=(4, 3), dtype=float32, value=[[-0.18212603 -0.5039175  -0.2043107 ]
  [ 0.5113777   0.66832054 -0.72778296]
  [-0.7988674  -0.6770984  -0.19285746]
  [-0.6106162   0.4812315   0.6228734 ]]>,
 <Variable path=sequential_3/dense_4/bias, shape=(3,), dtype=float32, value=[-0.04581157  0.01211583  0.03369574]>]

In [76]:
predicts = model.predict(x=data)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step


In [77]:
predicts.shape  #> (n_samples, n_classes)

(150, 3)

In [78]:
predicts[:5]

array([[0.640031  , 0.33577916, 0.02418982],
       [0.6297952 , 0.3257787 , 0.04442608],
       [0.6194201 , 0.34833953, 0.03224038],
       [0.6051582 , 0.35450494, 0.04033674],
       [0.6313848 , 0.34748653, 0.02112871]], dtype=float32)

In [79]:
model.evaluate(x=data, y=target)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.6643 - sparse_categorical_accuracy: 0.7733  


[0.6642572283744812, 0.7733333110809326]

In [80]:
# epoch 횟수를 증가시켜서 훈련
model.fit(x=data, y=target, epochs=1_000, verbose=0)

In [81]:
model.evaluate(x=data, y=target)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1692 - sparse_categorical_accuracy: 0.9800 


[0.1691550761461258, 0.9800000190734863]