<a href="https://colab.research.google.com/github/JakeOh/202511_BD53/blob/main/lab_ml/ml18_cnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CNN(Convolutional Neural Network, 합성곱 신경망)

# Imports

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from scipy.signal import convolve, convolve2d, correlate, correlate2d
from sklearn.datasets import load_sample_image
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

import keras

# 1차원 합성곱 연산(1-D Convolution)

In [8]:
x = np.arange(1, 5)
print(x)

[1 2 3 4]


In [9]:
y = np.array([1, 2])
print(y)

[1 2]


In [10]:
y_flip = np.flip(y)
print(y_flip)

[2 1]


## `convolve()` 함수

scipy 패키지의 convolve 함수는 y를 반전시키고 합성곱 연산을 수행.

In [11]:
result = convolve(x, y, mode='valid')  # valid 모드 -> 결과 배열은 x보다 크기가 줄어듦.
print(result)

[ 4  7 10]


In [12]:
result = convolve(x, y, mode='same')  # same 모드 -> 결과 배열은 x와 크기가 같음.
print(result)

[ 1  4  7 10]


In [13]:
# full mode: 배열 x의 모든 원소가 합성곱 연산에 같은 비율로 참여하도록 패딩을 넣는 방법.
result = convolve(x, y, mode='full')
print(result)

[ 1  4  7 10  8]


## `correlate()` 함수

교차 상관(cross-correlate): scipy 패키지는 배열 y를 반전시키지 않고 배열 x와 합성곱 연산을 수행.

In [14]:
result = correlate(x, y, mode='valid')
print(result)

[ 5  8 11]


In [15]:
result = correlate(x, y, mode='same')
print(result)

[ 2  5  8 11]


In [16]:
result = correlate(x, y, mode='full')
print(result)

[ 2  5  8 11  4]


# 2차원 합성곱(2-D Convolution)

In [17]:
x = np.arange(1, 17).reshape((4, 4))
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [18]:
y = np.array([[0, 1], [2, 0]])
print(y)

[[0 1]
 [2 0]]


In [19]:
y_flip = np.flip(y)
print(y_flip)

[[0 2]
 [1 0]]


## `convolve2d()` 함수

In [20]:
result = convolve2d(x, y, mode='valid')
print(result)

[[ 9 12 15]
 [21 24 27]
 [33 36 39]]


In [21]:
result = convolve2d(x, y, mode='same')
print(result)

[[ 0  1  2  3]
 [ 2  9 12 15]
 [10 21 24 27]
 [18 33 36 39]]


In [22]:
result = convolve2d(x, y, mode='full')
print(result)

[[ 0  1  2  3  4]
 [ 2  9 12 15  8]
 [10 21 24 27 12]
 [18 33 36 39 16]
 [26 28 30 32  0]]


## `correlate2d()` 함수

In [23]:
result = correlate2d(x, y, mode='valid')
print(result)

[[12 15 18]
 [24 27 30]
 [36 39 42]]


# 이미지 배열과 합성곱 연산

Python에서 이미지

*   숫자들의 배열
*   숫자들의 스케일:
    *   0 ~ 255 정수 스케일
    *   0.0 ~ 1.0 실수 스케일
*   배열의 모양
    *   흑백 이미지: (height, width) 모양의 2차원 배열.
    *   컬러 이미지: (height, width, channels) 모양의 3차원 배열.
        *   투명도가 없는 이미지: (height, width, 3). channels = rgb
        *   투명도가 있는 이미지: (height, width, 4). channels = rgba
    *   Keras 패키지에서는 합성곱 층에서 흑백 이미지를 사용할 때, 컬러 이미지처럼 3차원 배열을 사용.
        *   Keras 패키지는 흑백 이미지를 (height, width, 1) 모양의 3차원 배열로 취급.